#pragma config(Sensor, in1,    liftPotent,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  baseEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  baseEncoderRight, sensorQuadEncoder)
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBase,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBase,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftSet1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftSet2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftMogo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightMogo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftChainBar,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightChainBar, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool Phase1BaseMovementIsNotDone = true;
	bool Phase1LiftMovementIsNotDone = true;

	while(Phase1BaseMovementIsNotDone || Phase1LiftMovementIsNotDone)
	{

		if(fabs(SensorValue[baseEncoderLeft]) >= 970 && fabs(SensorValue[baseEncoderRight]) >= 970) //Ex: Base moving
		{

			Phase1BaseMovementIsNotDone = false;

		}

		else
		{

			motor[leftBase] = 115;
			motor[rightBase] = 115;

		}

		if(SensorValue[liftPotent] <= 3326.11) //Ex: Lift lifting
		{

			Phase1LiftMovementIsNotDone = false;

		}

		else
		{

			motor[liftSet1] = 100;
			motor[liftSet2] = 100;

		}

	}

}
