#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftPotent,     sensorPotentiometer)
#pragma config(Sensor, in2,    mogoPotent,     sensorPotentiometer)
#pragma config(Sensor, in3,    clawPotent,     sensorNone)
#pragma config(Sensor, I2C_1,  leftBaseEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightBaseEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  leftChainBarEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  rightChainBarEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBase,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightBase,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           liftSet1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftSet2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftMogo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightMogo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftChainBar,  tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           rightChainBar, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool Phase1BaseMovementIsNotDone = true;
	bool Phase1LiftMovementIsNotDone = true;
	bool Phase3LiftMovementIsNotDone = true;
	bool Phase3BaseMovementIsNotDone = true;


	while(Phase1BaseMovementIsNotDone || Phase1LiftMovementIsNotDone) //Phase one, go to stationary goal
	{
		

		if(fabs(SensorValue[leftBaseEncoder]) >= 970 && fabs(SensorValue[rightBaseEncoder]) >= 970) //Base moving
		{

			Phase1BaseMovementIsNotDone = false;

		}

		else
		{

			motor[leftBase] = 115;
			motor[rightBase] = 115;

		}

		if(SensorValue[liftPotent] <= 3326.11) //Lift lifting
		{

			Phase1LiftMovementIsNotDone = false;

		}

		else
		{

			motor[liftSet1] = 100;
			motor[liftSet2] = 100;

		}
		

	}
	
	while(true)//chainbar will go 
	{
 		if(SensorValue[rightChainBarEncoder] >= 9)
 		{
			motor[leftChainBar]= 127;
			motor[rightChainBar]=127;
		}
		else
		{
			motor[leftChainBar]=0;
			motor[rightChainBar]=0;
		}
  }
	while(true)
	{
		if(SensorValue[clawPotent] < 9)
		{
			motor[clawMotor]= 127;
		}
		else
		{
			motor[clawMotor]= 0;
		}
	}
	
	while(true)//chainbar will go 
	{
 		if(SensorValue[rightChainBarEncoder] <= 9)
 		{
			motor[leftChainBar]=  -127;
			motor[rightChainBar]= -127;
		}
		else
		{
			motor[leftChainBar]=0;
			motor[rightChainBar]=0;
		}
  }
		
	while(true)
	{
		if(SensorValue[leftBaseEncoder] >= 9 && SensorValue[rightBaseEncoder] >= 9) // base turning
		{
			motor[leftBase] = 115;
			motor[rightBase]= -115;
		}
		
		else
		{
			motor[leftBase] = 0;
			motor[rightBase] = 0;
		}
	}
	
	while(Phase3BaseMovementIsNotDone || Phase3LiftMovementIsNotDone)
	{
		if(fabs(SensorValue[left]) >= 970 && fabs(SensorValue[]) >= 970)
		

}
