#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBase,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBase,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftSet1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftSet2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftMogo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightMogo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftChainBar,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightChainBar, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true)
	{

		if(vexRT[Ch3] > 10 || vexRT[Ch3] < -10) //Control for left side of base
		{

			motor[leftBase] = vexRT[Ch3];

		}

		else
		{

			motor[leftBase] = 0;

		}

		if(vexRT[Ch2] > 10 || vexRT[Ch2] < -10) //Control for right side of base
		{

			motor[rightBase] = vexRT[Ch2];

		}

		else
		{

			motor[rightBase] = 0;

		}

		if(vexRT[Btn7U] == 1) //Controls Mogo manipulator
		{

			motor[leftMogo] = 65;
			motor[rightMogo] = 65;

		}

		else if(vexRT[Btn7D] == 1) //Controls Mogo manipulator
		{

			motor[leftMogo] = -65;
			motor[rightMogo] = -65;

		}

		else
		{

			motor[leftMogo] = 0;
			motor[rightMogo] = 0;

		}

		if(vexRT[Btn5U] == 1) //Controls dr4b lift
		{

			motor[liftSet1] = 120;
			motor[liftSet2] = 120;

		}

		else if(vexRT[Btn5D] == 1) //Controls dr4b lift
		{

			motor[liftSet1] = -120;
			motor[liftSet2] = -120;

		}

		else
		{

			motor[liftSet1] = 0;
			motor[liftSet2] = 0;

		}

		if(vexRT[Btn6U] == 1) //Controls chain bar lift
		{

			motor[leftChainBar] = 100;
			motor[rightChainBar] = 100;

		}

		else if(vexRT[Btn6D] == 1) //Controls chain bar lift
		{

			motor[leftChainBar] = -100;
			motor[rightChainBar] = -100;

		}

		else
		{

			motor[leftChainBar] = 0;
			motor[rightChainBar] = 0;

		}

		if(vexRT[Btn8U] == 1) //Controls claw
		{

			motor[clawMotor] = 127;

		}

		else if(vexRT[Btn8D] == 1) //Controls claw
		{

			motor[clawMotor] = -127;

		}

		else
		{

			motor[clawMotor] = 0;

		}

	}

}
