#pragma config(Sensor, dgtl1,  baseEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftBase,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBase,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftSet1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftSet2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftMogo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightMogo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftChainBar,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightChainBar, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	bool Phase1BaseMovementIsNotDone = true;
	bool Phase1LiftMovementIsNotDone = true;

	while(Phase1BaseMovementIsNotDone || Phase1LiftMovementIsNotDone)
	{

		if(SensorValue[baseEncoder] >= 360 /*Desired Sesnor Input*/) //Ex: Base moving
		{

			Phase1BaseMovementIsNotDone = false;

		}

		else
		{

			motor[leftBase] = 120;

		}

		if(SensorValue[liftEncoder] >= 360 /*Desired Sensor Input*/) //Ex: Lift lifting
		{

			Phase1LiftMovementIsNotDone = false;

		}

		else
		{

			motor[liftSet1] = 120;

		}

	}

}
